language: go

go:
  - 1.7

before_install:
  - go get -u github.com/stretchr/testify/assert
  - go get -u github.com/krolaw/dhcp4
  - go get -u github.com/hashicorp/logutils
  - go get -v github.com/golang/lint/golint

script:
  - go test -v go list ./... | grep -v vendor -cover
