language: go

go:
  - 1.8
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get -d ./...

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci 
  - go test -race -coverprofile=coverage.out -covermode=atomic -v github.com/simar7/xserver

after_success:
  - bash <(curl -s https://codecov.io/bash)