language: go

go:
  - 1.7
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get -d ./...

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci 
  - go test -v github.com/simar7/xserver -cover
